import unicodedata

CATEGORIAS_AUTO = {

    
        # 🍔 ALIMENTAÇÃO
        "Alimentação": [
            "ifood",
            "food",
            "lanche",
            "pizza",
            "hamburguer",
            "hamburgueria",
            "restaurante",
            "comida",
            "mercado",
            "supermercado",
            "padaria",
            "lanchonete",
            "refeicao",
            "almoco",
            "jantar",
            "cafe",
            "bebida",
            "sorvete",
            "acai",
            "delivery",
            "marmita",
            "burger",
            "burger king",
            "mcdonalds",
            "mc donalds",
            "bk",
            "subway",
            "habibs",
            "kfc",
            "bobs",
            "outback",
            "starbucks",
            "girafas",
            "hortifruti",
            "sacolao",
            "sacolão",
            "dominos",
            "pizza hut",
            "china in box",
            "spoleto",
            "giraffas",
            "habib's",
            "jeronimo",
            "bullguer",
            "madeiro",
            "frango assado",
            "bacio di latte",
            "kopenhagen",
            "cacau show",
            "chocolates brasil cacau",
        ],
        # 🛒 SUPERMERCADO
        "Supermercado": [
            "extra",
            "carrefour",
            "pao de acucar",
            "pão de açúcar",
            "guanabara",
            "zona sul",
            "assai",
            "assai atacadista",
            "atacadao",
            "big",
            "sam's club",
            "mundial",
            "supermarket",
            "rede economia",
            "princesa",
            "hortifruti",
            "supermercado",
            "mercado",
        ],
        # 🚗 TRANSPORTE
        "Transporte": [
            "uber",
            "99",
            "taxi",
            "onibus",
            "metro",
            "combustivel",
            "gasolina",
            "etanol",
            "diesel",
            "posto",
            "ipiranga",
            "shell",
            "petrobras",
            "br",
            "estacionamento",
            "pedagio",
            "passagem",
            "jae",
            "bilhete único",
            "corrida",
            "transporte",
            "blablacar",
            "movida",
            "localiza",
            "unidas",
            "cabify",
            "in drive",
        ],
        # ⛽ POSTO
        "Combustível": [
            "posto",
            "ipiranga",
            "shell",
            "petrobras",
            "br",
            "ale",
            "ale combustivel",
            "rede graal",
            "gasolina",
            "etanol",
            "diesel",
        ],
        # 🏠 MORADIA
        "Moradia": [
            "aluguel",
            "condominio",
            "condomínio",
            "conta de luz",
            "energia",
            "agua",
            "água",
            "internet",
            "wifi",
            "gás",
            "gas",
            "iptu",
            "imovel",
            "imóvel",
            "reforma",
            "manutencao",
            "manutenção",
            "faxina",
            "diarista",
            "material de construcao",
            "leroy merlin",
            "casa show",
            "telhanorte",
        ],
        # 📱 CONTAS FIXAS
        "Contas Fixas": [
            "telefone",
            "celular",
            "claro",
            "vivo",
            "tim",
            "oi",
            "plano",
            "mensalidade",
            "boleto",
            "fatura",
            "debito automatico",
            "débito automático",
            "net",
            "sky",
            "directv",
            "internet",
        ],
        # 💳 ASSINATURAS
        "Assinaturas": [
            "netflix",
            "spotify",
            "amazon prime",
            "prime",
            "youtube premium",
            "deezer",
            "hbo max",
            "disney",
            "globoplay",
            "apple tv",
            "icloud",
            "google one",
            "onedrive",
            "chatgpt",
            "openai",
            "canva",
            "notion",
            "figma",
        ],
        # 🎮 LAZER
        "Lazer": [
            "cinema",
            "filme",
            "show",
            "evento",
            "bar",
            "cerveja",
            "chopp",
            "balada",
            "jogo",
            "games",
            "steam",
            "xbox",
            "playstation",
            "psn",
            "epic games",
            "viagem",
            "passeio",
            "teatro",
            "boliche",
            "kart",
            "reserva cultural",
        ],
        # 🏥 SAÚDE
        "Saúde": [
            "farmacia",
            "farmácia",
            "drogaria",
            "droga",
            "drogasil",
            "droga raia",
            "pacheco",
            "remedio",
            "remédio",
            "medico",
            "médico",
            "consulta",
            "exame",
            "hospital",
            "clinica",
            "clínica",
            "plano de saude",
            "plano de saúde",
            "dentista",
            "odontologico",
            "psicologo",
            "psicólogo",
            "terapia",
            "laboratorio",
            "laboratório",
            "fleury",
            "delboni",
        ],
        # 🧠 EDUCAÇÃO
        "Educação": [
            "curso",
            "faculdade",
            "mensalidade",
            "escola",
            "material",
            "livro",
            "apostila",
            "udemy",
            "alura",
            "rocketseat",
            "dio",
            "estudo",
            "certificacao",
            "certificação",
            "bootcamp",
            "pós",
            "graduação"
            "universidade",
        ],
        # 🛒 COMPRAS
        "Compras": [
            "amazon",
            "mercado livre",
            "mercadolivre",
            "shopee",
            "shein",
            "aliexpress",
            "magazine luiza",
            "magalu",
            "casas bahia",
            "pontofrio",
            "americanas",
            "submarino",
            "kabum",
            "terabyte",
            "roupa",
            "tenis",
            "calca",
            "camisa",
            "sapato",
            "acessorio",
            "loja",
            "shopping",
            "compra",
        ],
        # 👕 ROUPAS
        "Roupas": [
            "renner",
            "riachuelo",
            "cea",
            "c&a",
            "zara",
            "hering",
            "nike",
            "adidas",
            "puma",
            "centauro",
            "track field",
            "roupa",
            "tenis",
            "camisa",
            "calca",
            "sapato",
            "vestuario",
        ],
        # 🐶 PETS
        "Pets": [
            "pet",
            "ração",
            "racao",
            "veterinario",
            "veterinário",
            "banho",
            "tosa",
            "cachorro",
            "gato",
            "petshop",
            "cobasi",
            "petz",
            "areia",
        ],
        # 💼 TRABALHO
        "Trabalho": [
            "ferramenta",
            "equipamento",
            "notebook",
            "computador",
            "mouse",
            "teclado",
            "software",
            "licenca",
            "licença",
            "dominio",
            "domínio",
            "servidor",
            "hosting",
            "hospedagem",
            "aws",
            "digitalocean",
            "vercel",
        ],
        # 💸 IMPOSTOS
        "Impostos e Taxas": [
            "imposto",
            "taxa",
            "multa",
            "ipva",
            "licenciamento",
            "detran",
            "juros",
            "tarifa",
            "imposto de renda",
        ],
        # 🎁 PRESENTES
        "Presentes": [
            "presente",
            "aniversario",
            "aniversário",
            "natal",
            "dia das maes",
            "dia das mães",
            "namorados",
            "casamento",
        ],
        # 💰 INVESTIMENTOS
        "Investimentos": [
            "investimento",
            "acao",
            "ações",
            "fii",
            "tesouro",
            "cdb",
            "cripto",
            "bitcoin",
            "ethereum",
            "binance",
            "coinbase",
            "renda fixa",
            "renda variavel",
            "clear",
            "xp",
            "rico",
        ],
        # 🔁 TRANSFERÊNCIAS
        "Transferências": [
            "pix",
            "mandei",
            "enviei",
            "pix enviado",
            "pix recebido",
            "transferencia",
            "transferência",
            "ted",
            "doc",
            "envio",
            "recebido",
            "pagamento",
            "transfer",
            "remessa",
            "deposito",
            "depósito",
            "saque",
            "retirada",
            "ajuste",
            "acerto",
            "repasse",
            "boleto pix",
            "qr code",
            "qrcode",
            "chave pix",
        ],
        # 🏦 BANCOS
        "Bancos": [
            "nubank",
            "inter",
            "itau",
            "itaú",
            "bradesco",
            "santander",
            "caixa",
            "bb",
            "banco do brasil",
            "neon",
            "c6",
            "c6 bank",
            "picpay",
            "mercado pago",
            "paypal",
            "wise",
            "banco",
            "conta",
            "saldo",
            ],

}


def normalizar(texto: str):
    texto = texto.lower().strip()
    texto = unicodedata.normalize("NFD", texto)
    texto = "".join(c for c in texto if unicodedata.category(c) != "Mn")
    return texto


def detectar_categoria(descricao: str):
    descricao = normalizar(descricao)

    for categoria, palavras in CATEGORIAS_AUTO.items():
        for palavra in palavras:
            palavra = normalizar(palavra)

            if palavra in descricao:
                return categoria

    return "Outros"


def listar_categorias_auto():
    return list(CATEGORIAS_AUTO.keys())
